Check that file exists before trying to deploy it

diff --git a/templates/deploy_with_tomcat_manager.sh.erb b/templates/deploy_with_tomcat_manager.sh.erb
--- a/templates/deploy_with_tomcat_manager.sh.erb
+++ b/templates/deploy_with_tomcat_manager.sh.erb
@@ -1,4 +1,17 @@
 #!/bin/bash
 
 WAR_FILE=$1
+
+if [ -z "$WAR_FILE" ]; then
+  echo "Usage: deploy_with_tomcat_manager.sh [<full path to local .war]"
+  exit 1
+fi
+
+if [ ! -f "$WAR_FILE" ];
+then
+    echo "File not found!"
+    exit 1
+fi
+
+
 curl -4 -u <%=tomcat_admin_user%>:<%=tomcat_admin_password%> "http://localhost:<%=tomcat_port%>/manager/text/deploy?path=/&tag=tomcat7_rhel&war=file:$WAR_FILE&update=true"
