Wait at most 80 seconds for the smoke test to pass

diff --git a/templates/run_smoke_test.sh.erb b/templates/run_smoke_test.sh.erb
--- a/templates/run_smoke_test.sh.erb
+++ b/templates/run_smoke_test.sh.erb
@@ -4,19 +4,17 @@ COUNTER=0
 while curl -L -s -o /dev/null -w "%{http_code}" localhost:<%=tomcat_port%> | grep -v 200; do
   echo Waiting for <%=application_name%> to respond...
   let COUNTER=COUNTER+1
-  if [  $COUNTER -ge 10 ]; then
-        break
+  if [  $COUNTER -ge 40 ]; then
+    break
   fi
   sleep 2
 done
 
 curl -L -s -o /dev/null -w "%{http_code}" localhost:<%=tomcat_port%> | grep 200 > /dev/null
 if [[ "$?" -eq 0 ]]; then
-        echo "Smoke test on <%=application_name%> succeeded"
-        exit 0
+  echo "Smoke test on <%=application_name%> succeeded"
+  exit 0
 else
-   	echo "Smoke test on <%=application_name%> failed"
-        exit 1
+  echo "Smoke test on <%=application_name%> failed"
+  exit 1
 fi
-
-
